# Enable C++ support
language: cpp
addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
    packages:
      - cmake
      - g++-4.8
      - g++-4.9
      - g++-5
      - clang-3.5
      - clang-3.6
      - clang-3.7
      - clang-3.8
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.8
    - compiler: gcc
      env: COMPILER=g++-4.9
    - compiler: gcc
      env: COMPILER=g++-5
    - compiler: clang
    - compiler: clang
      env: COMPILER=clang++-3.5
    - compiler: clang
      env: COMPILER=clang++-3.6
    - compiler: clang
      env: COMPILER=clang++-3.7
    - compiler: clang
      env: COMPILER=clang++-3.8
script:
  - mkdir build
  - cd build
  - export CXX=$COMPILER
  - cmake ..
  - make -j2
