# Enable C++ support
language: cpp
sudo: true
dist: trusty
compiler: 
  - gcc
  - clang
before_install:
  - sudo apt-get install -qq libopenmpi-dev openmpi-bin
script:
  - mkdir build
  - cd build
  - export CXX=$COMPILER
  - cmake ..
  - make -j2
after_script:
  - ctest .
