# Enable C++ support
language: cpp
sudo: true
dist: trusty
python: 
  - "2.7"
  - "3.5"
git:
    submodules: false
before_install:
  - ./dev/setup_travis
matrix:
  include:
    - compiler: gcc
    - compiler: gcc
      env: INSTALL_MPI=true
    - compiler: clang
    - compiler: clang
      env: INSTALL_MPI=true
script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - ./dev/travis_cpp_test
  - ./dev/travis_py_test
