# Enable C++ support
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env: COMPILER=clang++-3.6
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - kalakris-cmake
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - cmake
    #         - g++-5
    #   env: COMPILER=g++-5
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - kalakris-cmake
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7
    #       packages:
    #         - cmake
    #         - clang-3.7
    #   env: COMPILER=clang++-3.7
script:
  - mkdir build
  - cd build
  - export CXX=$COMPILER
  - cmake ..
  - make -j2
