# Enable C++ support
language: cpp
sudo: true
dist: trusty
python: 
  - "2.7"
  - "3.5"
matrix:
  include:
    - compiler: gcc
      before_install:
      - ./dev/install_travis_gcc
    - compiler: gcc
      before_install:
      - ./dev/install_travis_gcc
      - sudo apt-get install -qq libopenmpi-dev openmpi-bin
    - compiler: clang
      before_install:
      - ./dev/install_travis_gcc
    - compiler: clang
      before_install:
      - ./dev/install_travis_gcc
      - sudo apt-get install -qq libopenmpi-dev openmpi-bin
script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - ./dev/travis_cpp_test
  - ./dev/travis_py_test
