# Enable C++ support
language: cpp
sudo: true
dist: trusty
python: 
  - "2.7"
  - "3.5"
matrix:
  include:
    - compiler: gcc
    - compiler: gcc
      before_install:
      - sudo apt-get install -qq libopenmpi-dev openmpi-bin
    - compiler: clang
      before_install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get -qq update
      - sudo apt-get -qq install g++-4.9
    - compiler: clang
      before_install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get -qq update
      - sudo apt-get -qq install g++-4.9
      - sudo apt-get install -qq libopenmpi-dev openmpi-bin
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - cd ..
  - sudo python setup.py install
after_script:
  - ctest .
  - mkdir python_test
  - cd python_test
  - python -c "import taskloaf"
