site_name: taskloaf
docs_dir: docs
theme: yeti
pages:
    - Home: index.md
    - About: about.md
    - Installation: installation.md
    - Design: design.md
    - Quick Start:
        - Python: python-quick-start.md
        - C++: cpp-quick-start.md
